/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

import com.formdev.flatlaf.FlatClientProperties;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import net.miginfocom.swing.MigLayout;
import raven.application.Application;
import raven.toast.Notifications;

/**
 *
 * @author Zoky_liva
 */
public class AjoutPersonne extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    
    java.util.Date datenaiss;
    java.sql.Date Mydatenaiss;
    
    public String statut;
    public String situation;
    public String diplome;
    /**
     * Creates new form AjoutPersonne
     */
    public AjoutPersonne() throws IOException {
        initComponents();
        conn = ConnectionBD.connect();
        init();
    }
    
    private void init() {
        setLayout(new MigLayout("al center center"));

        lbtitre.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font");
        
//        txtPass.putClientProperty(FlatClientProperties.STYLE, ""
//                + "showRevealButton:true;"
//                + "showCapsLock:true");
        btnadd.putClientProperty(FlatClientProperties.STYLE, ""
                + "borderWidth:0;"
                + "focusWidth:0");
        txtim.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "IM du personne");
        txtnm.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nom");
        txtpn.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Prenom(s)");
        txtcont.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Contact ou mail");
        txtnc.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nom du conjoint");
        txtpc.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Prenom du conjoint");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneladd = new raven.application.form.other.PanelAddPersonne();
        lbtitre = new javax.swing.JLabel();
        lbdipl = new javax.swing.JLabel();
        txtim = new javax.swing.JTextField();
        lbcat = new javax.swing.JLabel();
        lbmont = new javax.swing.JLabel();
        lbnum = new javax.swing.JLabel();
        txtpn = new javax.swing.JTextField();
        txtnm = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        lbmont1 = new javax.swing.JLabel();
        txtcont = new javax.swing.JTextField();
        datenais = new com.toedter.calendar.JDateChooser();
        lbmont2 = new javax.swing.JLabel();
        combodipl = new javax.swing.JComboBox<>();
        lbmont3 = new javax.swing.JLabel();
        combostat = new javax.swing.JComboBox<>();
        lbmont4 = new javax.swing.JLabel();
        combosit = new javax.swing.JComboBox<>();
        txtnc = new javax.swing.JTextField();
        lbdipl1 = new javax.swing.JLabel();
        txtpc = new javax.swing.JTextField();
        lbdipl2 = new javax.swing.JLabel();

        lbtitre.setText("Ajouter nouvelle personne");

        lbdipl.setText("Nom");

        lbcat.setText("Prenom");

        lbmont.setText("Date de naissance");

        lbnum.setText("IM");

        btnadd.setText("Ajouter");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        lbmont1.setText("Contact");

        lbmont2.setText("Diplome");

        combodipl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                combodiplMousePressed(evt);
            }
        });

        lbmont3.setText("Statut");

        combostat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vivant", "Decede" }));

        lbmont4.setText("Situation");

        combosit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marie(e)", "Divorce(e)", "Veuve(veuf)" }));

        lbdipl1.setText("Nom du conjoint");

        lbdipl2.setText("Prenom du conjoint");

        javax.swing.GroupLayout paneladdLayout = new javax.swing.GroupLayout(paneladd);
        paneladd.setLayout(paneladdLayout);
        paneladdLayout.setHorizontalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbdipl2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdipl1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmont4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmont3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmont2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datenais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbmont1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtim)
                    .addComponent(lbdipl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnm)
                    .addComponent(txtpn)
                    .addComponent(lbmont, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtitre, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtcont)
                    .addComponent(lbcat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combodipl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combostat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combosit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnc)
                    .addComponent(txtpc))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        paneladdLayout.setVerticalGroup(
            paneladdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneladdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtitre)
                .addGap(18, 18, 18)
                .addComponent(lbnum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbdipl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbcat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbmont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datenais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbmont1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbmont2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combodipl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbmont3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combostat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbmont4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combosit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbdipl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbdipl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnadd)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(paneladd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneladd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
       datenaiss = datenais.getDate();
       Mydatenaiss = new java.sql.Date(datenaiss.getTime());
       
        
       try{
            String sql = "insert into personne (im,nom,prenom,datenais,diplome,contact,statut,situation,nomconjoint,prenomconjoint) "
                    + "values (?,?,?,?,?,?,?,?,?,?)";
            diplome = combodipl.getSelectedItem().toString();
            statut = combostat.getSelectedItem().toString();
            situation = combosit.getSelectedItem().toString();
            
            ps = conn.prepareStatement(sql);
            //ps.setString(1, txtim.getText());
            ps.setObject(1, txtim.getText());
            ps.setString(2, txtnm.getText());
            ps.setString(3, txtpn.getText());
            ps.setDate(4, Mydatenaiss);
            ps.setString(5, diplome);
            ps.setString(6, txtcont.getText());
            ps.setString(7, statut);
            ps.setString(8, situation);
            ps.setString(9, txtnc.getText());
            ps.setString(10, txtpc.getText());
            
            ps.executeUpdate();
            Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Personne ajouter");
            Application.showForm(new ListesPersonnes());
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void combodiplMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combodiplMousePressed
        try{
            String sql = "select distinct diplome from tarif";
            Statement st = conn.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
            combodipl.addItem(rs.getString("diplome"));
			}
		}
		catch(Exception ex){
			System.out.println(ex.getMessage());
		}
    }//GEN-LAST:event_combodiplMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JComboBox<String> combodipl;
    private javax.swing.JComboBox<String> combosit;
    private javax.swing.JComboBox<String> combostat;
    private com.toedter.calendar.JDateChooser datenais;
    private javax.swing.JLabel lbcat;
    private javax.swing.JLabel lbdipl;
    private javax.swing.JLabel lbdipl1;
    private javax.swing.JLabel lbdipl2;
    private javax.swing.JLabel lbmont;
    private javax.swing.JLabel lbmont1;
    private javax.swing.JLabel lbmont2;
    private javax.swing.JLabel lbmont3;
    private javax.swing.JLabel lbmont4;
    private javax.swing.JLabel lbnum;
    private javax.swing.JLabel lbtitre;
    private javax.swing.JPanel paneladd;
    private javax.swing.JTextField txtcont;
    private javax.swing.JTextField txtim;
    private javax.swing.JTextField txtnc;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtpc;
    private javax.swing.JTextField txtpn;
    // End of variables declaration//GEN-END:variables
}
