/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package raven.application.form.other;

import com.formdev.flatlaf.FlatClientProperties;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.miginfocom.swing.MigLayout;
import raven.application.Application;
import raven.toast.Notifications;

/**
 *
 * @author Zoky_liva
 */
public class UpdateTarif extends javax.swing.JPanel {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    /**
     * Creates new form UpdateTarif
     */
    public UpdateTarif() throws IOException {
        initComponents();
        conn = ConnectionBD.connect();
        Recuper();
        init();
    }
    
    private void init() {
        setLayout(new MigLayout("al center center"));

        lbtitre.putClientProperty(FlatClientProperties.STYLE, ""
                + "font:$h1.font");
        
        btnupdate.putClientProperty(FlatClientProperties.STYLE, ""
                + "borderWidth:0;"
                + "focusWidth:0");
        txtnum.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Numero");
        txtdipl.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nom diplome");
        txtcat.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Categorie");
        txtmont.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Montant(AR)");
    }
    
    public void Recuper() throws IOException{
        ListesTarif tf = new ListesTarif();
        tf.Deplace();
        
        try{
            String rec = tf.gettableresult();
            String sql = "select * from tarif where num_tarif = '"+rec+"' ";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            if(rs.next()){
                String t1 = rs.getString("num_tarif");
                txtnum.setText(t1);
                String t2 = rs.getString("diplome");
                txtdipl.setText(t2);
                String t3 = rs.getString("categorie");
                txtcat.setText(t3);
                String t4 = rs.getString("montant");
                txtmont.setText(t4);
//                String t5 = rs.getString("num_tarif");
//                txtnumUpdate.setText(t5);
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelupdate = new raven.application.form.other.PanelUpdateTarif();
        lbtitre = new javax.swing.JLabel();
        lbdipl = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        lbcat = new javax.swing.JLabel();
        lbmont = new javax.swing.JLabel();
        lbnum = new javax.swing.JLabel();
        txtcat = new javax.swing.JTextField();
        txtdipl = new javax.swing.JTextField();
        txtmont = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();

        lbtitre.setText("Modification du tarif");

        lbdipl.setText("Diplome");

        lbcat.setText("Categorie");

        lbmont.setText("Montant");

        lbnum.setText("Numero tarif");

        btnupdate.setText("Mettre a jour");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelupdateLayout = new javax.swing.GroupLayout(panelupdate);
        panelupdate.setLayout(panelupdateLayout);
        panelupdateLayout.setHorizontalGroup(
            panelupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelupdateLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(panelupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbnum, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnum)
                    .addComponent(lbdipl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdipl)
                    .addComponent(lbcat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcat)
                    .addComponent(lbmont, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmont)
                    .addComponent(lbtitre, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelupdateLayout.setVerticalGroup(
            panelupdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelupdateLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbtitre)
                .addGap(26, 26, 26)
                .addComponent(lbnum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbdipl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdipl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbcat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lbmont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnupdate)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(panelupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(panelupdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String t1 = txtnum.getText();
        String t2 = txtdipl.getText();
        String t3 = txtcat.getText();
        String t4 = txtmont.getText();
        
        String sql = "update tarif set diplome = '"+t2+"',categorie = '"+t3+"',montant = '"+t4+"' where num_tarif = '"+t1+"'";
        
        try{
           ps = conn.prepareStatement(sql);
           ps.execute();
           Notifications.getInstance().show(Notifications.Type.WARNING, Notifications.Location.TOP_CENTER, "Tarif modifier");
           Application.showForm(new ListesTarif());
        }catch(Exception e){
            System.out.println(e.getMessage());
        }    
    }//GEN-LAST:event_btnupdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel lbcat;
    private javax.swing.JLabel lbdipl;
    private javax.swing.JLabel lbmont;
    private javax.swing.JLabel lbnum;
    private javax.swing.JLabel lbtitre;
    private javax.swing.JPanel panelupdate;
    private javax.swing.JTextField txtcat;
    private javax.swing.JTextField txtdipl;
    private javax.swing.JTextField txtmont;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
